//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyMVVM.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string ProjName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string RoleWork { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
